### PR TITLE
Ot281 23

### PR DESCRIPTION
**Pull request by arielmeragelman**
Fixing OT281 23 with errors

### CODE REVIEW

**Comment by arielmeragelman** [comment]
wrong pull request

**Comment by arielmeragelman** [comment]
please review thanks

**Comment by fgpalacios** [comment]
Favor de resolver los conflictos
airflow/dags/C_uni_de_palermo.py
airflow/dags/C_uni_nacional_de_jujuy.py

**Comment by fgpalacios** [comment]
resuelto

**Pull request merged**
